export const Suggestions = [
  '@builtin',
  '@category:',
  '@disabled',
  '@enabled',
  '@featured',
  '@id:',
  '@installed',
  '@linked',
  '@mcpservers',
  '@most-popular',
  '@outdated',
  '@recentlypublished',
  '@recommended',
  '@sort:installs',
  '@workspaceunsupported',
]
