export const HandleContextMenu = 'handleContextMenu'
export const HandlePointerDown = 'handlePointerDown'
export const HandleTouchStart = 'handleTouchStart'
export const HandleWheel = 'handleWheel'
export const HandleExtensionsInput = 'handleExtensionsInput'
