export const HandleContextMenu = 'handleContextMenu'
export const HandlePointerDown = 'handlePointerDown'
export const HandleTouchStart = 'handleTouchStart'
export const HandleWheel = 'handleWheel'
export const HandleExtensionsInput = 'handleExtensionsInput'
export const HandleClearSearchResults = 'handleClearSearchResults'
export const HandleClickFilter = 'handleClickFilter'
