export const extensionCategories = [
  'AI',
  'Azure',
  'Chat',
  'Data Science',
  'Debuggers',
  'Education',
  'Extension Packs',
  'Formatters',
  'Keymaps',
  'Language Packs',
  'Linters',
  'Machine Learning',
  'Notebooks',
  'Other',
  'Programming Languages',
  'SCM Providers',
  'Snippets',
  'Testing',
  'Themes',
  'Visualization',
]
